### ISSUE TITLE
yolo v4 implement

### ISSUE THREAD

**Issue by how-how1202** [myelintek/mlsteamsupport#14]
how to urn Yolo-v4 with gpu

**Comment by simonschuang** [comment]
The error message shown when compiling yolov4
![1594017539709](https://user-images.githubusercontent.com/2860098/86566354-179a1a00-bf9c-11ea-8c49-cc290d7a58a4.png)

please work around this issue by removing following links and restart lab.
```
rm -rf /usr/lib/x86_64-linux-gnu/libcuda.so /usr/lib/x86_64-linux-gnu/libcuda.so.1
```

**Comment by how-how1202** [comment]
it works! ths!
