### ISSUE TITLE
當關閉視窗時，在Lab中的訓練將被停止

### ISSUE THREAD

**Issue by how-how1202** [myelintek/mlsteamsupport#15]
1.不小心關閉視窗，造成lab中訓練模型停止?
2.使用第二台電腦，能否編輯或使用lab訓練?

**Comment by simonschuang** [comment]
1. 視窗關閉訓練應繼續進行, 請提供您操作的步驟供我們釐清問題.
2. 可以透過第二台電腦連接相同Lab環境, 但目前不支援real-time collaberation, 表示兩台電腦對相同Lab操作不會互相看到即時畫面.

**Comment by simonschuang** [comment]
adding reopen lab window example.

![reopenlab](https://user-images.githubusercontent.com/2860098/86703687-b4b18d00-c046-11ea-992e-b2d99da15a30.gif)

**Comment by hsiaohsuanlin** [comment]
I can reproduce this issue.

**Comment by hsiaohsuanlin** [comment]
have been resolved on MLSteam V3.6.1
![Screen Shot 2020-07-08 at 2 21 54 PM](https://user-images.githubusercontent.com/65696388/86884654-7390aa00-c126-11ea-9a35-904dcb9ef11a.png)
