### ISSUE TITLE
Questions related to system specs

### ISSUE THREAD

**Issue by simonschuang** [myelintek/mlsteamsupport#24]
1.	系統建立Project的文字格式怎麼定義(大小寫數字字元符號還有限制)?
2.	Lab開啟到完整跑完Jupyter時間大概是多少(是否有一個比較好的時間提供我們寫Spec)
3.	在Dataset裡面解壓縮除了支援 tar, tgz , tar.gz , zip 還有別的嗎?

**Comment by mm25712423** [comment]
1. 
    * Project name rules
        * 長度 3 - 32 字元
        * 接受 '_', '-' 特殊字元(under line, dash) (特殊字元不可連續出現)
        * 不可接受ip型式
        * 不可符號開頭或結尾
    * Username rules
        * 長度 3 - 63 字元
        * 可使用電子信箱格式
        * 接受 '_', '.', ','特殊字元(under line, dot, comma) (特殊字元不可連續出現)
        * 不可接受ip型式
        * 不可符號開頭或結尾
    * Password rules
        * 長度 6 - 63 字元
        * 不可接受ip型式
        *  符號隨意
2. 待觀察
3. 目前僅支援 (tar, tgz , tar.gz , zip) 四種格式
